- name: Deploy Dockerized Application
  hosts: all
  become: no
  tasks:
    - name: Pull the latest image from DockerHub
      docker_image:
        name: "noamjorno/myapp"
        source: pull
        tag: latest
          
    - name: Stop and remove existing container (if exists)
      docker_container:
        name: my-app-container
        state: absent

    - name: Run the new container
      docker_container:
        name: my-app-container
        image: "noamjorno/myapp:latest"
        state: started
        ports:
          - "80:80"